name: expense_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^0.67.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  flutter_slidable: ^3.1.0
  flutter_heatmap_calendar: ^1.0.5
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  percent_indicator: ^4.2.3
  modal_bottom_sheet: ^3.0.0
  intl: ^0.19.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

assets:
    - lib/assets/icons/

flutter:
  uses-material-design: true
